### PR TITLE
note find_iocs won't work within multiprocessing pool

### PR DESCRIPTION
**Pull request by wesinator**
https://anothercybersecurityblog.wordpress.com/2019/11/19/the-downside-of-python-multiprocessing-daemon-childs/

### CODE REVIEW

**Comment by crahan** [comment]
@wesinator  not to deviate too much from this particular issue, but I found this PR as I was experiencing similar issues when using `ioc-finder` in a Slack bot app. The `slackclient` library also uses multiprocessing so I seem to be hitting the same problems.

What is strange though is that it's only happening in Python 3.8.0 for me. When I run the exact same code in Python 3.7.2 virtualenv it works perfectly fine. Do you happen to know if anything significantly changed between Python 3.7.2 and 3.8.0 when it comes to threading and multiprocessing?

**Comment by wesinator** [comment]
> @wesinator not to deviate too much from this particular issue, but I found this PR as I was experiencing similar issues when using `ioc-finder` in a Slack bot app. The `slackclient` library also uses multiprocessing so I seem to be hitting the same problems.
> 
> What is strange though is that it's only happening in Python 3.8.0 for me. When I run the exact same code in a Python 3.7.2 virtualenv it works perfectly fine. Do you happen to know if anything significantly changed between Python 3.7.2 and 3.8.0 when it comes to threading and multiprocessing?

Yes -  are you on macOS ? 

See https://bugs.python.org/issue33725 and multiprocessing documentation:
https://docs.python.org/dev/library/multiprocessing.html#contexts-and-start-methods

"Changed in version 3.8: On macOS, the spawn start method is now the default. The fork start method should be considered unsafe as it can lead to crashes of the subprocess. See bpo-33725."

**Comment by crahan** [comment]
That's exactly my situation. I am indeed running macOS. Thanks for confirming! 

I've worked around this by manually calling the relevant parse functions I need.

**Comment by fhightower** [comment]
Thanks for the input @wesinator and @crahan ! I'll be addressing this in #65 by switching to use https://docs.python.org/3/library/concurrent.futures.html .

**Comment by wesinator** [comment]
closing per #65

**Pull request closed without merging**
